on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-k6-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: ./perf
        run: docker build -t my-k6-test .

      - name: Run k6 Tests
        run: docker run --rm my-k6-test